### ISSUE TITLE
Fail to install in IOS platform

### ISSUE THREAD

**Issue by dshark95** [BlinkID/blinkid-cordova#156]
Failed to install 'blinkid-cordova': Error: Hook failed with error code 1: /Users/tmlee/bdi/Container_App/plugins/blinkid-cordova/scripts/initIOSFramework.sh
    at /Users/tmlee/.nvm/versions/node/v14.17.0/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:224:23
    at _rejected (/Users/tmlee/.nvm/versions/node/v14.17.0/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /Users/tmlee/.nvm/versions/node/v14.17.0/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/Users/tmlee/.nvm/versions/node/v14.17.0/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/Users/tmlee/.nvm/versions/node/v14.17.0/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /Users/tmlee/.nvm/versions/node/v14.17.0/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/Users/tmlee/.nvm/versions/node/v14.17.0/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/tmlee/.nvm/versions/node/v14.17.0/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
    
    Hi, I was trying to install blinkid-cordova for ios and android, android is fine but ios fail to install.

**Comment by dshark95** [comment]
Solve, by install wget using brew
